# Generated by Django 2.2.11 on 2021-02-06 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('father_name', models.CharField(max_length=40)),
                ('caste', models.CharField(max_length=30)),
                ('aadhaar', models.CharField(max_length=12)),
                ('items', models.IntegerField()),
                ('lending_amount', models.FloatField()),
                ('total_intrest', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('item_id', models.CharField(max_length=40)),
                ('weight', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lending_amount', models.FloatField()),
                ('intrest', models.FloatField()),
                ('remarks', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewelry.Customer')),
            ],
        ),
    ]
