# Generated by Django 2.2.11 on 2021-02-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0004_auto_20210206_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='items',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
