# Generated by Django 2.2.11 on 2021-02-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0007_auto_20210207_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='intrest',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lending_amount',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
